#!/bin/bash

# Use common vars from .env
source .env

# Ensure exit is properly trapped
trap "exit $?" TERM

# Set sane path
PATH="/bin:/usr/bin:/sbin:/usr/sbin"

# Set error Handlers
error_exit() {
	echo "$(date) - ERROR - ${ERRMSG}"
	exit 1
}

# Ensure requirements are installed
reqs_check() {
	# Check for dependencies
	ERRMSG="Dependency missing. Recommend 'sudo apt-get --no-install-recommends install apache2-utils wireguard'"
	which htpasswd &>/dev/null || error_exit
	which wg &>/dev/null || error_exit
}

# Generate key pairs
gen_keys() {
	# Generate keys, first run only.

	PRIVKEY_WG_CLIENT="$(wg genkey)"
	echo "PRIVKEY_WG_CLIENT=${PRIVKEY_WG_CLIENT}" >> .env

	PUBKEY_WG_CLIENT="$(echo ${PRIVKEY_WG_CLIENT} | wg pubkey)"
	echo "PUBKEY_WG_CLIENT=${PUBKEY_WG_CLIENT}" >> .env
	
	PRIVKEY_WG_SERVER="$(wg genkey)"
	echo "PRIVKEY_WG_SERVER=${PRIVKEY_WG_SERVER}" >> .env
	
	PUBKEY_WG_SERVER="$(echo ${PRIVKEY_WG_SERVER} | wg pubkey)"
	echo "PUBKEY_WG_SERVER=${PUBKEY_WG_SERVER}" >> .env
}

# Generate server and client config files
gen_wg_conf() {
	# Create wg0.conf for client
	cat > ${DOCKER_DATA_PATH}/wireguard/wg0.conf <<EOF
[Interface]
PrivateKey = ${PRIVKEY_WG_CLIENT}
Address = 10.1.0.2/24

[Peer]
PublicKey = ${PUBKEY_WG_SERVER}
AllowedIPs = 10.1.0.0/24
Endpoint = ${WG_HOSTNAME}:${WG_PORT}
PersistentKeepalive = 20
EOF
	chmod 600 ${DOCKER_DATA_PATH}/wireguard/wg0.conf

	# Create wg0.conf for server
	cat > ${DOCKER_DATA_PATH}/server-wg0.conf <<EOF
[Interface]
Address = 10.1.0.1/24
ListenPort = ${WG_PORT}
PrivateKey = ${PRIVKEY_WG_SERVER}

[Peer]
PublicKey = ${PUBKEY_WG_CLIENT}
AllowedIPs = 10.1.0.2/24
EOF

	# Create iptables for server
	cat > ${DOCKER_DATA_PATH}/rules.v4 <<EOF
# Generated by iptables-save v1.8.7 on Mon Apr  8 13:44:44 2024
*filter
:INPUT ACCEPT [5491:5315337]
:FORWARD ACCEPT [5507:5129419]
:OUTPUT ACCEPT [2908:515161]
COMMIT
# Completed on Mon Apr  8 13:44:44 2024
# Generated by iptables-save v1.8.7 on Mon Apr  8 13:44:44 2024
*nat
:PREROUTING ACCEPT [109587:16129068]
:INPUT ACCEPT [10020:470412]
:OUTPUT ACCEPT [65:4936]
:POSTROUTING ACCEPT [2837:163426]
-A PREROUTING -p tcp -m multiport --dports 80,443,25565 -j DNAT --to-destination 10.1.0.2
-A POSTROUTING -j MASQUERADE
COMMIT
EOF
}

# Configure e-mail for traefik ACME / LetsEncrypt
config_le() {
	ERRMSG="Failed to update LetsEncrypt Email"
	sed -i.bak "s#email: .*#email: ${LE_EMAIL}#g" ${DOCKER_DATA_PATH}/traefik/traefik.yml || error_exit
}

# Set basic auth for traefik
config_auth() {
	ERRMSG="Failed to set auth password for traefik"
	USER_AUTH="$(htpasswd -nb ${AUTH_USER} ${AUTH_PASSWORD} | sed -e s/\\$/\\$\\$/g | head -1)"
	sed -i.bak "s#traefik-auth.basicauth.users=.*#traefik-auth.basicauth.users=${USER_AUTH}\"#g" docker-compose.yml || error_exit
}

reqs_check
test -n "${PUBKEY_WG_SERVER}" || gen_keys
gen_wg_conf
config_le
config_auth
touch ${DOCKER_DATA_PATH}/traefik/acme.json && chmod 600 ${DOCKER_DATA_PATH}/traefik/acme.json

echo "Finished setup. Please run 'sudo docker network create dmz'"
